config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  #validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])        #
  end

  def new
    @task = Task.new(params[:task])
    @task.save
  end

  def create
    Task.create(user_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(user_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

private

  def set_task
    @task = Task.find(params[:id])
  end

  def user_params
    params.require(:task).permit(:name, :content, :deadline)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form:html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :deadline %>
  <%= f.text_field :deadline %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
   <%= f.label :deadline %>
  <%= f.text_field :deadline %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
  <% @tasks.each do |task| %>
  <h2><%= task.name %></h2>
  <p><%= task.content %></p>
  <p><%= task.deadline %></p>
  <p><%= link_to "c'est quoi cette tâche?", task_path(task) %></p>
  <p><%= link_to "modifier la tâche", edit_task_path(task) %></p>
  <% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :deadline %>
  <%= f.text_field :deadline %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.content %></p>
<p><%= @task.deadline %></p>
<p><%= link_to "retour à la liste des tâches", tasks_path %></p>